name: CI pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [test, build, kodi-kontroll]
    if: github.ref == 'refs/head/master'
    steps:
      - name: lae kood alla
        uses: actions/checkout@v4

      - name: teata edukast deployst
        run: |
          echo "koik testid labisid"
          echo "rakendus on valmis"
          echo "keskkond: production"
          echo "commit: ${{ github.sha }}"




  build:
      name: docker build kontroll
      runs-on: ubuntu-latest
      steps:
        - name: lae kood alla
          uses: actions/checkout@v4
        
        - name: ehite dev image
          run: docker compose --profile dev build

        - name: ehita prod image
          run: docker compose --profile prod build

        - name: ehita test image
          run: docker compose --profile test build
  kodi-kontroll:
    runs-on: ubuntu-latest

    steps:
      - name: Lae kood alla
        uses: actions/checkout@v4

      - name: Paigalda Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Paigalda sõltuvused
        run: npm install

      - name: Kontrolli süntaksi vigu
        run: |
          node --check src/server.js
          node --check src/routes/users.js
          node --check src/routes/menu.js
          node --check src/routes/orders.js

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Lae kood alla
        uses: actions/checkout@v4

      - name: Paigalda Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Paigalda sõltuvused
        run: npm install

      - name: Käivita rakendus
        run: node src/server.js &

      - name: Oota serveri käivitumist
        run: sleep 3

      - name: Käivita testid
        run: node src/test.js
